name: Deploy Terraform Template

on:
  workflow_call:
    inputs:
      environment_name:
        required: false
        type: string
      google_client_id:
        required: false
        type: string
      google_client_secret:
        required: false
        type: string
      linkedin_client_id:
        required: false
        type: string
      linkedin_client_secret:
        required: false
        type: string
  # push:
  #   branches:
  #     - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step: Set AWS credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AwsAcarinOIDCRole }}
          aws-region: ${{ inputs.AWSDefaultRegion }}
          role-session-name: "GitHubActions"
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0 
      
      - name: Init, Plan, and Apply Terraform
        run: |
          # cd terraform
          terraform init
          terraform plan -var="environment_name=${{ inputs.environment_name }}" -var="google_client_id=${{ inputs.google_client_id }}" -var="google_client_secret=${{ inputs.google_client_secret }}" -var="linkedin_client_id=${{ inputs.linkedin_client_id }}" -var="linkedin_client_secret=${{ inputs.linkedin_client_secret }}"
          terraform apply -auto-approve -var="environment_name=${{ inputs.environment_name }}" -var="google_client_id=${{ inputs.google_client_id }}" -var="google_client_secret=${{ inputs.google_client_secret }}" -var="linkedin_client_id=${{ inputs.linkedin_client_id }}" -var="linkedin_client_secret=${{ inputs.linkedin_client_secret }}"
